from .admin_password_model import AdminPasswordModel
from .medicine_model import MedicineModel
from .non_recognized_patients_model import NonRecognizedPatientsModel
from .patient_model import PatientModel
